### ISSUE TITLE
Migrace rešit přes cakephp/phinx

### ISSUE THREAD

**Issue by endrsmar** [xnukes/fpvspots#2]
Na všech projektech používám pro migrace cakephp/phinx balíček. Jednoduše trackuje současnou verzi, jednotlivé změny jsou ve vlastních souborech, umožňuje rollbacky na konkrétní verzi, umožňuje seedovat databázi daty. Nechcete to použít i tady?
https://github.com/cakephp/phinx

**Comment by xnukes** [comment]
Použijeme :) 👍

**Comment by endrsmar** [comment]
Integrováno v rámci https://github.com/xnukes/fpvspots/pull/3
